### ISSUE TITLE
NoClassDefFoundError on first boot

### ISSUE THREAD

**Issue by KnowledgeGarden** [alekcz/datahike-starter#1]
datahike-starter.core=> (require '[datahike.api :as d])
Execution error (NoClassDefFoundError) at java.lang.Class/forName0 (Class.java:-2).
Could not initialize class datahike.api__init

In my experience, this could be any of a number of problems, some of which are based on the fact that some java libraries, such as JAXB have to be imported separately - but I'm not seeing that issue specifically.

This is an M1 MacBook Pro with jdk 15. Not enough information in the error message to debug this, and too new to clojure to dive much deeper.

**Comment by KnowledgeGarden** [comment]
'lein run' does this
Exception in thread "main" Syntax error compiling at (datahike_starter/core.clj:1:1).
...
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.Class.forName0(Native Method)
...
We still do not know where the issue is cropping up. Hunch is somewhere in this:
`(ns datahike-starter.core
    (:require [datahike.api :as d]
              [datahike-firebase.core])    
  (:gen-class))`

**Comment by KnowledgeGarden** [comment]
Built a quick datahike-test and replicated the core header, and left [datahike-firebase.core] out. That test has the usual "foo" main; it says "Hello World". 
I added [alekcz/datahike-firebase "0.2.0-SNAPSHOT"] to project.clj
Now, it fails thusly:
Syntax error (ClassNotFoundException) compiling at (datahike_test/core.clj:1:1).
net.jpountz.lz4.LZ4FrameOutputStream

the full net.jpountz.lzr 1.3.0 jar is in my local maven repo.

**Comment by alekcz** [comment]
@KnowledgeGarden just seeing this now. Sorry. I'll have a looksee in a bit.

**Comment by alekcz** [comment]
@KnowledgeGarden turns out `datahike` and `datahike-firebase` use different versions of `datahike` now. I've removed `datahike-firebase`. It's not required. I was using it to persist my changes when I was learning `datahike`. 

Everything should be peachy now
